# Generated by Django 4.1.7 on 2023-12-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/default-user.png', max_length=20000, null=True, upload_to='profiles/'),
        ),
    ]
